sudo apt-get install build-essential
sudo apt-get install bison
sudo apt-get install flex
sudo apt-get install libgmp3-dev
sudo apt-get install libmpc-dev
sudo apt-get install libmpfr-dev
sudo apt-get install textinfo
sudo apt-get install libcloog-isl-dev
sudo apt-get install libisl-dev
sudo apt-get install textinfo
